### ISSUE TITLE
Erreur 403 

### ISSUE THREAD

**Issue by devwald** [ebohm-up1/opilaissezpasser#1]
Bonjour,

Pouvez vous m'indiquer si l'application de génération des laisser passer (cpge) est toujours fonctionnelle avec la dernière version d'Apogée ?

Cf. https://github.com/UnivParis1/opilaissezpasser

En effet, impossible de la faire fonctionner cette année et en l'absence de logs impossible de comprendre ce qui se passe.

Merci d'avance.

Cdt.

PS : 
![ahaebloggjeojffp](https://user-images.githubusercontent.com/9694150/68138462-e4911980-ff28-11e9-8a4b-91d7fc020de0.jpeg)
Ci-dessous mon erreur

**Comment by ebohm-up1** [comment]
Bonjour,

Une mise à jour du dépôt permet de fonctionner sur la version du web service suivante:
webservicesclient520lba .

Concernant l'erreur 403, je vous invite à vérifier les droits d'accès vers le web service que vous avez renseigné dans le fichier de configuration :

"configUrlServices.properties"

Quelques tests fonctionnels ont été effectués sur la branche master, les laisser-passer ont bien été enregistrés.

Bien cordialement.
